### ISSUE TITLE
lError: local variable 'd_output' referenced before assignment

### ISSUE THREAD

**Issue by hiddengearz** [gwen001/myrecon.py#3]
Hello,

I tested your recon script out this weekend, it worked once and then after that I got the following error:

```user@server:~/tools/myrecon.py$ ./myrecon.py -d a.domain.I.removed -o test4
Traceback (most recent call last):
  File "./myrecon.py", line 129, in <module>
    app.init()
  File "/home/user/tools/myrecon.py/modules/app.py", line 56, in init
    func.parseargs( self )
  File "/home/user/tools/myrecon.py/modules/functions.py", line 69, in parseargs
    app.setOutputDirectory( d_output )
UnboundLocalError: local variable 'd_output' referenced before assignment
```

This seems to be a error in the python script, not sure If I'm missing anything :/

Ubuntu 18.04
requirements installed as well as most of the "mods"

**Comment by hiddengearz** [comment]
Results from the first time I ran it (I've since installed phantomjs, ffuf, subjack & aquatone)

```user@server:~/tools/myrecon.py$ python3 myrecon.py -d a.domain -o test3
[+] output directory is: test3
[+] 1 domains found.
[+] saved in test3/domains
[+] looking for subdomains...
[*] findomain -t a.domain
[-] error occurred: Command 'findomain -t a.domain' returned non-zero exit status 127.
[+] 0 hosts found.
[+] resolving...
[+] 0 ips found.
[+] 0 hosts alive found
[+] 0 dead hosts found, cleaning...
[+] creating urls...
[+] looking for endpoints...
[*] github-endpoints.py -d a.domain -s | tee -a raw_github-endpoints endpoints_grabbed 2>&1 >/dev/null &
[*] google-search.py -b -d -e 100 -t "site:a.domain" | tee -a raw_google-domain endpoints_grabbed 2>&1 >/dev/null &
[*] google-search.py -b -d -e 100 -t "site:a.domain inurl:&" | tee -a raw_google-domain endpoints_grabbed 2>&1 >/dev/null &
[*] waybackurls a.domain true /home/user/tools/myrecon.py/raw_wayback 2>&1 >/dev/null &
[-] error occurred: [Errno 2] No such file or directory: 'test3/urls_hosts'
user@server:~/tools/myrecon.py$ [+] output directory is: /home/user/tools/myrecon.py
[+] resume session, loading datas...
[+] output directory is: /home/user/tools/myrecon.py
[+] resume session, loading datas...
[+] output directory is: /home/user/tools/myrecon.py
[+] resume session, loading datas...
[+] output directory is: /home/user/tools/myrecon.py
[+] resume session, loading datas...
[+] output directory is: /home/user/tools/myrecon.py
[+] resume session, loading datas...
[+] output directory is: /home/user/tools/myrecon.py
[+] resume session, loading datas...
[+] output directory is: /home/user/tools/myrecon.py
[+] resume session, loading datas...
[+] output directory is: /home/user/tools/myrecon.py
[+] resume session, loading datas...
[-] error occurred: [Errno 2] No such file or directory: '/home/user/tools/myrecon.py/hosts'
[-] error occurred: [Errno 2] No such file or directory: '/home/user/tools/myrecon.py/hosts'
[-] error occurred: [Errno 2] No such file or directory: '/home/user/tools/myrecon.py/hosts'
[-] error occurred: [Errno 2] No such file or directory: '/home/user/tools/myrecon.py/hosts'
[-] error occurred: [Errno 2] No such file or directory: '/home/user/tools/myrecon.py/hosts'
[-] error occurred: [Errno 2] No such file or directory: '/home/user/tools/myrecon.py/hosts'
[-] error occurred: [Errno 2] No such file or directory: '/home/user/tools/myrecon.py/hosts'
[+] running mod: quickhits
[*] ffuf -u HFUZZ/WFUZZ -w "/home/user/tools/myrecon.py/urls":HFUZZ -w "/opt/SecLists/mine/myhardw.txt":WFUZZ -o raw_quickhits 2>&1 >/dev/null &
[+] running mod: cors
[*] cors.py -t 100 -u "/home/user/tools/myrecon.py/urls_hosts" 2>&1 >/dev/null &
[+] running mod: subto
[+] running mod: openredirect
[*] subjack -a -t 50 -timeout 20 -ssl -c "/opt/SecLists/mine/subjack_fingerprints.json" -v -w "/home/user/tools/myrecon.py/hosts" -o "subto/output" 2>&1 >/dev/null &
[-] error occurred: [Errno 2] No such file or directory: '/home/user/tools/myrecon.py/hosts'
[*] openredirect.py -t 100 -u "/home/user/tools/myrecon.py/endpoints" 2>&1 >/dev/null &
[+] running mod: smuggling
[*] smuggler.py -v 0 -t 50 -u "/home/user/tools/myrecon.py/urls_hosts" 2>&1 >/dev/null &
[+] running mod: xss
[+] running mod: crlf
[*] xss.py -t 10 -n "/usr/local/bin/phantomjs" -p "/opt/SecLists/mine/xss-myshort.txt" -u "/home/user/tools/myrecon.py/endpoints" 2>&1 >/dev/null &
[*] crlf.py -t 200 -u "/home/user/tools/myrecon.py/urls_hosts" 2>&1 >/dev/null &
[+] running mod: screenshot
[*] cat "/home/user/tools/myrecon.py/urls" | aquatone -out screenshot 2>&1 >/dev/null &
sh: 1: subjack: not found
sh: 1: ffuf: not found
sh: 1: aquatone: not found
cat: /home/user/tools/myrecon.py/urls: No such file or directory
[+] output directory is: /home/user/tools/myrecon.py
[+] resume session, loading datas...
[-] error occurred: [Errno 2] No such file or directory: '/home/user/tools/myrecon.py/hosts'
Traceback (most recent call last):
  File "/home/user/tools/myrecon.py/myrecon.py", line 130, in <module>
    app.run()
  File "/home/user/tools/myrecon.py/modules/app.py", line 63, in run
    self.runMod( mod_name )
  File "/home/user/tools/myrecon.py/modules/app.py", line 74, in runMod
    py_mod = imp.load_source( mod_name.capitalize(), mod_file)
  File "/usr/lib/python3.6/imp.py", line 172, in load_source
usage: xss.py [-h] [-a PATH] [-c COOKIES] [-n PHANTOM] [-o HOSTS]
              [-p PAYLOADS] [-s SCHEME] [-t THREADS] [-u URLS] [-v VERBOSE]
xss.py: error: phantomjs not found!
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/tools/myrecon.py/modules/googledorks.py", line 8, in <module>
    from goop import goop
ModuleNotFoundError: No module named 'goop'```

**Comment by gwen001** [comment]
Pretty simple, read the errors:

```
[-] error occurred: Command 'findomain -t a.domain' returned non-zero exit status 127.
```
Install findomain
https://github.com/Edu4rdSHL/findomain


```
ModuleNotFoundError: No module named 'goop'
```
pip3 install goop
